"use server";

import { redirect } from "next/navigation";
import { and, eq } from "drizzle-orm";

import { db } from "./db";
import { verifySession } from "./dal";
import { betaMods } from "../db/schema";
import { PromotionConfirmSchema } from "./definitions";
import { assertEditableMod, lockModForMutation, mutationMessage } from "./mod-lifecycle";
import { getAccountWriteError } from "./access";
import { notifyModFollowers } from "./notifications";

/**
 * Promotion actions (spec "Promotion flow", steps 1–5).
 *
 * The package itself is generated by lib/promotion.ts and downloaded from
 * /mods/[id]/promotion/download — this file only handles the confirmation
 * step: the author records the live Nexus page URL, and the beta mod becomes
 * read-only (`status = promoted`), dropping off Browse and linking to Nexus.
 */

export async function confirmPromotion(formData: FormData) {
  const betaModId = String(formData.get("betaModId") ?? "");
  if (!betaModId) redirect("/dashboard");

  const session = await verifySession();
  if (!db) redirect(`/mods/${betaModId}`);

  const validated = PromotionConfirmSchema.safeParse({
    nexusUrl: formData.get("nexusUrl"),
  });
  if (!validated.success) {
    redirect(`/mods/${betaModId}?promote=invalid`);
  }

  const url = new URL(validated.data.nexusUrl);
  if (url.protocol !== "https:" || url.username || url.password || !["www.nexusmods.com", "nexusmods.com"].includes(url.hostname) || !/^\/[^/]+\/mods\/\d+\/?$/.test(url.pathname)) {
    redirect(`/mods/${betaModId}?promote=invalid`);
  }
  let errorMessage = await getAccountWriteError(session.userId);
  if (!errorMessage) {
    try {
      await db.transaction(async tx => {
        const mod = await lockModForMutation(tx, betaModId);
        assertEditableMod(mod, session.userId);
        await tx.update(betaMods).set({ status: "promoted", nexusUrl: url.toString(), updatedAt: new Date() })
          .where(and(eq(betaMods.id, betaModId), eq(betaMods.ownerId, session.userId)));
        await notifyModFollowers(tx, betaModId, session.userId, `${mod.title} is now published on Nexus`, `/mods/${betaModId}`);
      });
    } catch (error) { errorMessage = mutationMessage(error); }
  }
  redirect(`/mods/${betaModId}${errorMessage ? `?feedback=${encodeURIComponent(errorMessage)}` : ""}`);
}
