"use server";

import { redirect } from "next/navigation";
import { and, eq } from "drizzle-orm";

import { db } from "./db";
import { verifySession } from "./dal";
import { betaMods } from "../db/schema";
import { PromotionConfirmSchema } from "./definitions";

/**
 * Promotion actions (spec "Promotion flow", steps 1–5).
 *
 * The package itself is generated by lib/promotion.ts and downloaded from
 * /mods/[id]/promotion/download — this file only handles the confirmation
 * step: the author records the live Nexus page URL, and the beta mod becomes
 * read-only (`status = promoted`), dropping off Browse and linking to Nexus.
 */

export async function confirmPromotion(formData: FormData) {
  const betaModId = String(formData.get("betaModId") ?? "");
  if (!betaModId) redirect("/dashboard");

  const session = await verifySession();
  if (!db) redirect(`/mods/${betaModId}`);

  // Owner-only.
  const modRows = await db
    .select({ id: betaMods.id, ownerId: betaMods.ownerId })
    .from(betaMods)
    .where(eq(betaMods.id, betaModId))
    .limit(1);
  const mod = modRows[0];
  if (!mod || mod.ownerId !== session.userId) {
    redirect(`/mods/${betaModId}`);
  }

  const validated = PromotionConfirmSchema.safeParse({
    nexusUrl: formData.get("nexusUrl"),
  });
  if (!validated.success) {
    redirect(`/mods/${betaModId}?promote=invalid`);
  }

  await db
    .update(betaMods)
    .set({
      status: "promoted",
      nexusUrl: validated.data.nexusUrl,
      updatedAt: new Date(),
    })
    .where(and(eq(betaMods.id, betaModId), eq(betaMods.ownerId, session.userId)));

  redirect(`/mods/${betaModId}`);
}